name: Auto Assign Issues to Project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@0.3.0
        with:
          project-url: https://github.com/users/Rishit-dagli/projects/6
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
